@baseUrl = http://localhost:3000
@contentType = application/json

###
# @name addProductToCart
# Endpoint to add a product to the cart.
POST {{baseUrl}}/cart
Content-Type: {{contentType}}

{
  "product_id": 5,
  "quantity": 4
}

###
# @name showCart
# Endpoint to list the products in the current cart.
GET {{baseUrl}}/cart
Content-Type: {{contentType}}

###
# @name addItem
# Endpoint to change the quantity of a product in the cart.
POST {{baseUrl}}/cart/add_item
Content-Type: {{contentType}}

{
  "product_id": 2,
  "quantity": 5
}


###
# @name removeItemFromCart
# Endpoint to remove a product from the cart.
DELETE {{baseUrl}}/cart/7
Content-Type: {{contentType}}
